build id
build;
build(
build[
build=

access id
access^
access:
access-
access_:

immo id
Immo:
immo:
immo/
immo)

if id
IF
if:
if>
if}

elif id
eliF
elif(
elif{
elif%

else id
else{
Else
else(
else#

flank id
_flank:
flank”
flank(
flank+

choice id
choice:
choice=
choice@
choice!

backup:
backup
backup(
backup&
backup1

for id
for*
for(
for<
for\

while id
while(
while{
while$
whilee

grind id
grind{
Grind
grind+
grind!

checkpoint id
checkpoint
checkpoint#
checkpoint(
checkpoint^

resume id
resume
resume#
resume.
resume;

recall id
recall#
recall*
recall”
recall-

dead id
dead:
dead,
dead&
dead|

generate id
generate:
generate[
generate}
Generate

play()
play
play{
play=
play2

shoot()
shoot
Shoot
shoot%
shoot.

shootNxt(
shootNxt
shootNXT
shootnxt:
shootnxt(

load()
Load()
load
load#
load`

loadNum()
loadnum()
loadNum:
loadNum%
loadNum0

rounds()
round()
rounds.
rounds+
rounds!

wipe()
wipe
WIPE
wipe[
wipe:

join_
join()
join+
join
join&

drop_
drop()
drop3
drop)
drop|

seek()
seeK
seek:
seek-
seek%

levelUp()
levelup
levelUp*
levelUp+
levelUp”

levelDown(
LevelDown
levelDown#
leveldown(
levelDown{

toHp()
tohp()
toHp=
toHp&
ToHp()

toXp()
toXP:
toXp:
toXp[
toXp)

toComms()
tocomms()
toComms.
toComms-
ToComms
